Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,67 +1,25 @@
 version: 2.1
-jobs:
-  build:
-    docker:
-      - image: python:3.6                   # similar to "image" in GitLab
-    steps:
-      - checkout
-      - run: |                              # similar to "script" in GitLab
-          pip install -r requirements.txt
-          python manage.py check
-
-  test:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: |
-          pip install -r requirements.txt
-          python manage.py test taskManager
-
-  secret_scanning:
-    machine: true
-    steps:
-      - run:
-          command: |
-            echo "my artifact file" > /tmp/myfile.txt
-            exit 1
-
-      - store_artifacts:
-          path: /tmp/myfile.txt
-          destination: artifact-file
-          
-  integration:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run:
-          command: |
-            echo "This is an integration step"
-          when: always    
-
-  prod:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: echo "This is a deploy step."
 
 workflows:
   version: 2
-  django:
+  build_deploy:
     jobs:
       - build
-      - test:
-          requires:
-            - build
-      - secret_scanning:
-          requires:
-            - test
-      - integration:
-          requires:
-            - secret_scanning
-      - prod:
-          type: approval
-          requires:
-            - integration
+
+jobs:
+  build:
+
+    docker:
+      - image: circleci/python:3.7.5
+    steps:
+      - checkout
+      - run:
+          name: Run commands
+          command: |
+              echo "I will exit fail status"
+              exit 1
+      - run:
+          name: Run on fail status
+          command: |
+              echo "I am result of above failed job"
+          when: on_fail
